### PR TITLE
Remove Perl 5.10 requirement.

### PR DESCRIPTION
**Pull request by topaz**

### CODE REVIEW

**Comment by gnustavo** [comment]
Hi Eric. I'm sorry to have left you waiting for so long.

Do you still need to use JIRA::REST in older Perls than 5.10? May I ask you in which platform you're using it?

I'd rather go forward instead of backward, so that I could start using newer perl constructs. But if the only 5.10 constructs I'm using are the ones you spotted I think I could live for a while with this little restriction. :-)

**Comment by topaz** [comment]
We do still use it; currently a locally-modified version of the library (with the changes in this pull request) is used on Perl 5.8.8 machines.  Because the change was so simple, I submitted it for inclusion.  If you want to use newer features instead, that's also fine, but since the only >5.8.8 feature used was //, I removed it. Thanks!

**Comment by gnustavo** [comment]
OK, then. I'll downgrade my requirement but I'll require v5.8.8 explicitly instead of leaving it open-ended.

I'll integrate this in the next release.

Thanks!

**Comment by gnustavo** [comment]
I just integrated a slightly modified commit on next: 09fddada

I'll be part of the next release.

Thanks!

**Pull request closed without merging**
