### PR TITLE
Allow use of 'agile' and 'servicedeskapi' endpoints on instantiation.…

### PR DESCRIPTION
**Pull request by evanernest**
… See: https://developer.atlassian.com/blog/2016/01/new-JIRA-Service-Desk-and-JIRA-Software-REST-APIs/

I have tested with the /rest/servicedeskapi endpoint. This would make the module more versatile.

### CODE REVIEW

**Comment by gnustavo** [comment]
Hi Evan. I'm sorry to have let you waiting for so long.

I haven't had a chance yet to experiment with the JSD and JS APIs. I hadn't realised they are just a "path" away from the JIRA Core API. So it seems a really good idea to make it possible to integrate them here.

But the way you suggested I'd have to choose a specific API during the JIRA::REST object construction. It would be better if we could use all three APIs with a single object.

What do you think if we extend the interface like this?

- If the $path argument to the methods GET, POST, PUT, and DELETE begins with "/rest" (i.e., it is "absolute") then I would use it as is.
- If not, then I would consider it a "relative path" of the core API and prefix it with "/rest/api/latest" as I do now.

The only problem is that currently I allow for the specification of a particular API version by means of the URL suffix during construction. One way to solve it would be to simply break backward compatibility and say that if one wants a particular version she should always use an absolute path. Another would be to keep the current constructor interface and extend it allowing for named arguments like this:

```
my $jira = JIRA::REST->new({
  url => 'https://jira.example.net',
  username => 'myself',
  password => 'kjhsdfg',
  rest_client_config => {...},
  api_version => '1.0',
});
```

Only the first three arguments above would be required. All others would be optional. This way one could specify the api_version. And this new constructor form is much more easily extensible.

I would like to see your thoughts on this.

**Comment by evanernest** [comment]
Hi Gustavo-

Thanks for getting back! I think the additional named arguments you proposed is the cleanest implementation, and it totally works for our purposes.

**Comment by gnustavo** [comment]
I think I was able to improve on my initial idea. Take a look at the commit I just pushed: 235197f.

I didn't implement the new form of the constructor because it's not needed. Now you can use absolute endpoint paths to completely specify the API/version/method to use. If the endpoint path passed to the REST methods does not begin with /rest I assume it's refering to JIRA's Core REST API and do exactly what JIRA::REST did before.

What do you think?

**Comment by evanernest** [comment]
Perfect. Works for me. Thanks for the help.

**Comment by gnustavo** [comment]
Great. I just released version 0.014 with this change.

Thanks!

**Pull request closed without merging**
